project.base-dir: file:///C:\Java\pro\Java\hello

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Market
    username: demo
    password: KoDYsyezIUoIQ6WR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  thymeleaf:
    prefix: ${project.base-dir}/src/main/resources/templates/
    cache: false
    mode: HTML5
    encoding: utf-8
    content-type: text/html
  resources:
    static-locations: ${project.base-dir}/src/main/resources/static/
    cache-period: 0
